/**
 * LiSA VOC QC Platform — InsForge Client Initialisation
 * ─────────────────────────────────────────────────────────────────────────────
 * Reads backend credentials exclusively from window.__LISA_CONFIG__,
 * which is injected at runtime by config.js (gitignored, never hardcoded here).
 *
 * Load order in every HTML page MUST be:
 *   1. <script src="config.js"></script>           ← sets window.__LISA_CONFIG__
 *   2. <script type="module" src="insforge-client.js"></script>  ← reads it
 * ─────────────────────────────────────────────────────────────────────────────
 */
// ── Graceful failure: validate config before attempting to create a client ──
let cfg = window.__LISA_CONFIG__;

// Fallback to window.ENV (generated by GitHub Actions deploy) if __LISA_CONFIG__ is not defined
if ((!cfg || typeof cfg !== 'object') && window.ENV && typeof window.ENV === 'object') {
  cfg = {
    baseUrl: window.ENV.INSFORGE_BASE_URL,
    anonKey: window.ENV.INSFORGE_ANON_KEY
  };
}

if (!cfg || typeof cfg !== 'object') {
  console.error(
    '[LiSA] Configuration error: window.__LISA_CONFIG__ is not defined.\n' +
    'Ensure config.js is loaded BEFORE insforge-client.js in your HTML.\n' +
    'Copy config.example.js → config.js and fill in your backend credentials.'
  );
  // Surface a visible warning on the page (non-crashing)
  document.addEventListener('DOMContentLoaded', () => {
    const banner = document.createElement('div');
    banner.style.cssText =
      'position:fixed;top:0;left:0;right:0;z-index:99999;background:#dc2626;color:#fff;' +
      'font-family:monospace;font-size:13px;padding:12px 20px;text-align:center;';
    banner.textContent =
      '⚠ LiSA Platform: Backend configuration is missing. ' +
      'Please set up config.js. Contact your system administrator.';
    document.body.prepend(banner);
  });
  // Export a null client so dependent modules don't crash
  window.insforgeClient = null;
} else {
  const missingKeys = ['baseUrl', 'anonKey'].filter(k => !cfg[k] || cfg[k].includes('your-'));
  if (missingKeys.length > 0) {
    console.warn(
      `[LiSA] Configuration warning: The following keys in window.__LISA_CONFIG__ ` +
      `appear to be placeholders: ${missingKeys.join(', ')}.\n` +
      `Update config.js with your real InsForge credentials.`
    );
  }

  // Use dynamic import so it works in non-module classic script environments
  import('./insforge-sdk.js').then((sdk) => {
    const client = sdk.createClient({
      baseUrl: cfg.baseUrl,
      anonKey: cfg.anonKey,
      timeout: 5000
    });

    window.insforgeClient = client;
    window.InsForgeClient = sdk.InsForgeClient;
  }).catch((err) => {
    console.error('[LiSA] Failed to load InsForge SDK dynamically:', err);
  });
}
